define({
    /* Please sort alphabetically */
    "root" : {
       AL : {name : "Albanie", fifa_code : "ALB"},
       AR : {name : "Argentine", fifa_code : "ARG"},
       AT : {name : "Autriche", fifa_code : "AUT"},
       AU : {name : "Australie", fifa_code : "AUS"},
       BA : {name : "Bosnie-et-Herzégovine", fifa_code : "BIH"},
       BE : {name : "Belgique", fifa_code : "BEL"},
       BG : {name : "Bulgarie", fifa_code : "BUL"},
       BR : {name : "Brésil", fifa_code : "BRA"},
       BY : {name : "Biélorussie", fifa_code : "BLR"},
       CH : {name : "Suisse", fifa_code : "SUI"},
       CI : {name : "Côte d'Ivoire", fifa_code : "CIV"},
       CL : {name : "Chili", fifa_code : "CHI"},
       CM : {name : "Cameroun", fifa_code : "CMR"},
       CO : {name : "Colombie", fifa_code : "COL"},
       CR : {name : "Costa Rica", fifa_code : "CRC"},
       CY : {name : "Chypre", fifa_code : "CYP"},
       CYM : {name : "Pays de Galles", fifa_code : "WAL"},
       CZ : {name : "République Tchèque", fifa_code : "CZE"},
       DE : {name : "Allemagne", fifa_code : "GER"},
       DK : {name : "Danemark", fifa_code : "DEN"},
       DZ : {name : "Algérie", fifa_code : "ALG"},
       EC : {name : "Equateur", fifa_code : "ECU"},
       EN : {name : "Angleterre", fifa_code : "ENG"},
       ES : {name : "Espagne", fifa_code : "ESP"},
       FI : {name : "Finlande", fifa_code : "FIN"},
       FR : {name : "France", fifa_code : "FRA"},
       GE : {name : "Georgie", fifa_code : "GEO"},
       GH : {name : "Ghana", fifa_code : "GHA"},
       GR : {name : "Grèce", fifa_code : "GRE"},
       HN : {name : "Honduras", fifa_code : "HON"},
       HR : {name : "Croatie", fifa_code : "CRO"},
       HU : {name : "Hongrie", fifa_code : "HUN"},
       IE : {name : "Irlande", fifa_code : "IRL"},
       IL : {name : "Israël", fifa_code : "ISR"},
       IS : {name : "Islande", fifa_code : "ISL"},
       IT : {name : "Italie", fifa_code : "ITA"},
       IR : {name : "Iran", fifa_code : "IRN"},
       JP : {name : "Japon", fifa_code : "JPN"},
       KR : {name : "Corée du Sud", fifa_code : "KOR"},
       MX : {name : "Mexique", fifa_code : "MEX"},
       NG : {name : "Nigéria", fifa_code : "NGA"},
       NIR : {name : "Irlande du Nord", fifa_code : "NIR"},
       NL : {name : "Pays-Bas", fifa_code : "NED"},
       NO : {name : "Norvège", fifa_code : "NOR"},
       PL : {name : "Pologne", fifa_code : "POL"},
       PT : {name : "Portugal", fifa_code : "POR"},
       RO : {name : "Roumanie", fifa_code : "ROU"},
       RS : {name : "Serbie", fifa_code : "SRB"},
       RU : {name : "Russie", fifa_code : "RUS"},
       SC : {name : "Ecosse", fifa_code : "SCO"},
       SE : {name : "Suède", fifa_code : "SWE"},
       SI : {name : "Slovénie", fifa_code : "SVN"},
       SK : {name : "Slovaquie", fifa_code : "SVK"},
       TR : {name : "Turquie", fifa_code : "TUR"},
       UA : {name : "Ukraine", fifa_code : "UKR"},
       UR : {name : "Uruguay", fifa_code : "URU"},
       US : {name : "USA", fifa_code : "USA"}
    }
});