define({
    /* Please sort alphabetically */
    "root" : {
       AL : "Albanie",
       AU : "Australie",
       AR : "Argentine",
       AT : "Autriche",
       BA : "Bosnie-et-Herzégovine",
       BE : "Belgique",
       BG : "Bulgarie",
       BR : "Brésil",
       BY : "Biélorussie",
       CH : "Suisse",
       CI : "Côte d'Ivoire",
       CL : "Chili",
       CM : "Cameroun",
       CO : "Colombie",
       CR : "Costa Rica",
       CY : "Chypre",
       CZ : "République Tchèque",
       DE : "Allemagne",
       DK : "Danemark",
       DZ : "Algérie",
       EC : "Equateur",
       EN : "Angleterre",
       ES : "Espagne",
       FI : "Finlande",
       FR : "France",
       GE : "Georgie",
       GH : "Ghana",
       GR : "Grèce",
       HN : "Honduras",
       HR : "Croatie",
       IL : "Israël",
       IT : "Italie",
       IR : "Iran",
       JP : "Japon",
       KR : "Corée du Sud",
       MX : "Mexique",
       NG : "Nigéria",
       NL : "Pays-Bas",
       NO : "Norvège",
       PT : "Portugal",
       RO : "Roumanie",
       RU : "Russie",
       SC : "Ecosse",
       SE : "Suède",
       SI : "Slovénie",
       TR : "Turquie",
       UA : "Ukraine",
       UR : "Uruguay",
       US : "USA"
    }
});